# ref: https://docs.travis-ci.com/user/languages/r/
language: r
cache:
  directories:
  - /home/travis/R/Library
r_packages:
- jsonlite
- httr
- testthat
- R6
- base64enc
- rlang
# uncomment below to install deps with devtools
install:
#- R -e 'devtools::install_deps(dep = T)'
- mkdir curl
- cd curl
- wget https://curl.haxx.se/download/curl-7.71.1.tar.gz
- sudo apt-get install libtool make libssl-dev
- tar -xvf curl-7.71.1.tar.gz
- cd curl-7.71.1
- ./buildconf
- ./configure --with-ssl
- sudo make
- sudo make install
- sudo mv /usr/bin/curl /usr/bin/curl.bak
- sudo cp /usr/local/bin/curl /usr/bin/curl
- which curl
- curl -Vv
- /usr/local/bin/curl -Vv
- cd ~/
script:
- R CMD build .
- R CMD check *tar.gz
- R CMD INSTALL *tar.gz
