# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test APIBillingPeriodUsageOut")

model.instance <- APIBillingPeriodUsageOut$new()

test_that("apiKey", {
  # tests for the property `apiKey` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`apiKey`, "EXPECTED_RESULT")
})

test_that("subscriptionStarted", {
  # tests for the property `subscriptionStarted` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`subscriptionStarted`, "EXPECTED_RESULT")
})

test_that("periodStarted", {
  # tests for the property `periodStarted` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`periodStarted`, "EXPECTED_RESULT")
})

test_that("periodEnded", {
  # tests for the property `periodEnded` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`periodEnded`, "EXPECTED_RESULT")
})

test_that("stripeCurrentPeriodEnd", {
  # tests for the property `stripeCurrentPeriodEnd` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`stripeCurrentPeriodEnd`, "EXPECTED_RESULT")
})

test_that("stripeCurrentPeriodStart", {
  # tests for the property `stripeCurrentPeriodStart` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`stripeCurrentPeriodStart`, "EXPECTED_RESULT")
})

test_that("billingStatus", {
  # tests for the property `billingStatus` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`billingStatus`, "EXPECTED_RESULT")
})

test_that("usage", {
  # tests for the property `usage` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`usage`, "EXPECTED_RESULT")
})

test_that("softLimit", {
  # tests for the property `softLimit` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`softLimit`, "EXPECTED_RESULT")
})

test_that("hardLimit", {
  # tests for the property `hardLimit` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`hardLimit`, "EXPECTED_RESULT")
})

