# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FirstLastNameDiasporaedOut")

model.instance <- FirstLastNameDiasporaedOut$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("firstName", {
  # tests for the property `firstName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`firstName`, "EXPECTED_RESULT")
})

test_that("lastName", {
  # tests for the property `lastName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`lastName`, "EXPECTED_RESULT")
})

test_that("score", {
  # tests for the property `score` (numeric)
  # Compatibility to NamSor_v1 Origin score value

  # uncomment below to test the property 
  #expect_equal(model.instance$`score`, "EXPECTED_RESULT")
})

test_that("ethnicityAlt", {
  # tests for the property `ethnicityAlt` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`ethnicityAlt`, "EXPECTED_RESULT")
})

test_that("ethnicity", {
  # tests for the property `ethnicity` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`ethnicity`, "EXPECTED_RESULT")
})

test_that("countryIso2", {
  # tests for the property `countryIso2` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`countryIso2`, "EXPECTED_RESULT")
})

