# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FirstLastNameIn")

model.instance <- FirstLastNameIn$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("firstName", {
  # tests for the property `firstName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`firstName`, "EXPECTED_RESULT")
})

test_that("lastName", {
  # tests for the property `lastName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`lastName`, "EXPECTED_RESULT")
})

