# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PersonalNameGeoIn")

model.instance <- PersonalNameGeoIn$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("countryIso2", {
  # tests for the property `countryIso2` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`countryIso2`, "EXPECTED_RESULT")
})

