# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test APIPlansOut")

model.instance <- APIPlansOut$new()

test_that("usage_ratio_for_dupplicates", {
  # tests for the property `usage_ratio_for_dupplicates` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`usage_ratio_for_dupplicates`, "EXPECTED_RESULT")
})

test_that("currency_iso3", {
  # tests for the property `currency_iso3` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`currency_iso3`, "EXPECTED_RESULT")
})

test_that("currency_symbol", {
  # tests for the property `currency_symbol` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`currency_symbol`, "EXPECTED_RESULT")
})

test_that("plans", {
  # tests for the property `plans` (APIPlanOut)

  # uncomment below to test the property 
  #expect_equal(model.instance$`plans`, "EXPECTED_RESULT")
})

