# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BatchFirstLastNamePhoneNumberGeoIn")

model.instance <- BatchFirstLastNamePhoneNumberGeoIn$new()

test_that("personalNamesWithPhoneNumbers", {
  # tests for the property `personalNamesWithPhoneNumbers` (FirstLastNamePhoneNumberGeoIn)

  # uncomment below to test the property 
  #expect_equal(model.instance$`personalNamesWithPhoneNumbers`, "EXPECTED_RESULT")
})

