# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BatchParsedFullNameIn")

model.instance <- BatchParsedFullNameIn$new()

test_that("personalNames", {
  # tests for the property `personalNames` (ParsedFullNameIn)

  # uncomment below to test the property 
  #expect_equal(model.instance$`personalNames`, "EXPECTED_RESULT")
})

