# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test APIKeyOut")

model.instance <- APIKeyOut$new()

test_that("api_key", {
  # tests for the property `api_key` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`api_key`, "EXPECTED_RESULT")
})

test_that("user_id", {
  # tests for the property `user_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`user_id`, "EXPECTED_RESULT")
})

test_that("admin", {
  # tests for the property `admin` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`admin`, "EXPECTED_RESULT")
})

test_that("vetted", {
  # tests for the property `vetted` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`vetted`, "EXPECTED_RESULT")
})

test_that("partner", {
  # tests for the property `partner` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`partner`, "EXPECTED_RESULT")
})

test_that("striped", {
  # tests for the property `striped` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`striped`, "EXPECTED_RESULT")
})

test_that("corporate", {
  # tests for the property `corporate` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`corporate`, "EXPECTED_RESULT")
})

test_that("disabled", {
  # tests for the property `disabled` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`disabled`, "EXPECTED_RESULT")
})

