# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BatchFirstLastNameOriginedOut")

model.instance <- BatchFirstLastNameOriginedOut$new()

test_that("personalNames", {
  # tests for the property `personalNames` (FirstLastNameOriginedOut)

  # uncomment below to test the property 
  #expect_equal(model.instance$`personalNames`, "EXPECTED_RESULT")
})

