# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BatchFirstLastNameGenderIn")

model.instance <- BatchFirstLastNameGenderIn$new()

test_that("personal_names", {
  # tests for the property `personal_names` (FirstLastNameGenderIn)

  # uncomment below to test the property 
  #expect_equal(model.instance$`personal_names`, "EXPECTED_RESULT")
})

