# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineObject")

model.instance <- InlineObject$new()

test_that("stripe_token", {
  # tests for the property `stripe_token` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`stripe_token`, "EXPECTED_RESULT")
})

test_that("stripe_email", {
  # tests for the property `stripe_email` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`stripe_email`, "EXPECTED_RESULT")
})

