# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BatchMatchPersonalFirstLastNameIn")

model.instance <- BatchMatchPersonalFirstLastNameIn$new()

test_that("personalNames", {
  # tests for the property `personalNames` (array[MatchPersonalFirstLastNameIn])

  # uncomment below to test the property 
  #expect_equal(model.instance$`personalNames`, "EXPECTED_RESULT")
})

