# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BatchFirstLastNameDiasporaedOut")

model.instance <- BatchFirstLastNameDiasporaedOut$new()

test_that("personal_names", {
  # tests for the property `personal_names` (FirstLastNameDiasporaedOut)

  # uncomment below to test the property 
  #expect_equal(model.instance$`personal_names`, "EXPECTED_RESULT")
})

