# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test APICounterV2Out")

model.instance <- APICounterV2Out$new()

test_that("api_key", {
  # tests for the property `api_key` (APIKeyOut)

  # uncomment below to test the property 
  #expect_equal(model.instance$`api_key`, "EXPECTED_RESULT")
})

test_that("api_service", {
  # tests for the property `api_service` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`api_service`, "EXPECTED_RESULT")
})

test_that("created_date_time", {
  # tests for the property `created_date_time` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`created_date_time`, "EXPECTED_RESULT")
})

test_that("total_usage", {
  # tests for the property `total_usage` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_usage`, "EXPECTED_RESULT")
})

test_that("last_flushed_date_time", {
  # tests for the property `last_flushed_date_time` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_flushed_date_time`, "EXPECTED_RESULT")
})

test_that("last_used_date_time", {
  # tests for the property `last_used_date_time` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_used_date_time`, "EXPECTED_RESULT")
})

test_that("service_features_usage", {
  # tests for the property `service_features_usage` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`service_features_usage`, "EXPECTED_RESULT")
})

