# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test APIServicesOut")

model.instance <- APIServicesOut$new()

test_that("apiServices", {
  # tests for the property `apiServices` (APIServiceOut)

  # uncomment below to test the property 
  #expect_equal(model.instance$`apiServices`, "EXPECTED_RESULT")
})

