# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NameMatchCandidatesOut")

model.instance <- NameMatchCandidatesOut$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("first_name", {
  # tests for the property `first_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`first_name`, "EXPECTED_RESULT")
})

test_that("last_name", {
  # tests for the property `last_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_name`, "EXPECTED_RESULT")
})

test_that("match_candidates", {
  # tests for the property `match_candidates` (NameMatchCandidateOut)

  # uncomment below to test the property 
  #expect_equal(model.instance$`match_candidates`, "EXPECTED_RESULT")
})

