# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NameMatchedOut")

model.instance <- NameMatchedOut$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("matchStatus", {
  # tests for the property `matchStatus` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`matchStatus`, "EXPECTED_RESULT")
})

test_that("score", {
  # tests for the property `score` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`score`, "EXPECTED_RESULT")
})

