# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test APIServiceOut")

model.instance <- APIServiceOut$new()

test_that("serviceName", {
  # tests for the property `serviceName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`serviceName`, "EXPECTED_RESULT")
})

test_that("serviceGroup", {
  # tests for the property `serviceGroup` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`serviceGroup`, "EXPECTED_RESULT")
})

test_that("costInUnits", {
  # tests for the property `costInUnits` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`costInUnits`, "EXPECTED_RESULT")
})

