# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BatchFirstLastNamePhoneNumberIn")

model.instance <- BatchFirstLastNamePhoneNumberIn$new()

test_that("personalNamesWithPhoneNumbers", {
  # tests for the property `personalNamesWithPhoneNumbers` (FirstLastNamePhoneNumberIn)

  # uncomment below to test the property 
  #expect_equal(model.instance$`personalNamesWithPhoneNumbers`, "EXPECTED_RESULT")
})

