# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RomanizedNameOut")

model.instance <- RomanizedNameOut$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("latin_name", {
  # tests for the property `latin_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`latin_name`, "EXPECTED_RESULT")
})

test_that("original_name", {
  # tests for the property `original_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`original_name`, "EXPECTED_RESULT")
})

test_that("source_language", {
  # tests for the property `source_language` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`source_language`, "EXPECTED_RESULT")
})

test_that("target_language", {
  # tests for the property `target_language` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`target_language`, "EXPECTED_RESULT")
})

test_that("source_script", {
  # tests for the property `source_script` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`source_script`, "EXPECTED_RESULT")
})

test_that("target_script", {
  # tests for the property `target_script` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`target_script`, "EXPECTED_RESULT")
})

test_that("score", {
  # tests for the property `score` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`score`, "EXPECTED_RESULT")
})

