# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PersonalNameGenderedOut")

model.instance <- PersonalNameGenderedOut$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("likelyGender", {
  # tests for the property `likelyGender` (character)
  # Most likely gender

  # uncomment below to test the property 
  #expect_equal(model.instance$`likelyGender`, "EXPECTED_RESULT")
})

test_that("genderScale", {
  # tests for the property `genderScale` (numeric)
  # Compatibility to NamSor_v1 Gender Scale M[-1..U..+1]F value

  # uncomment below to test the property 
  #expect_equal(model.instance$`genderScale`, "EXPECTED_RESULT")
})

test_that("score", {
  # tests for the property `score` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`score`, "EXPECTED_RESULT")
})

