# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PersonalNameParsedOut")

model.instance <- PersonalNameParsedOut$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("nameParserType", {
  # tests for the property `nameParserType` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`nameParserType`, "EXPECTED_RESULT")
})

test_that("nameParserTypeAlt", {
  # tests for the property `nameParserTypeAlt` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`nameParserTypeAlt`, "EXPECTED_RESULT")
})

test_that("firstLastName", {
  # tests for the property `firstLastName` (FirstLastNameOut)

  # uncomment below to test the property 
  #expect_equal(model.instance$`firstLastName`, "EXPECTED_RESULT")
})

test_that("score", {
  # tests for the property `score` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`score`, "EXPECTED_RESULT")
})

