# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test APIClassifierTaxonomyOut")

model.instance <- APIClassifierTaxonomyOut$new()

test_that("classifierName", {
  # tests for the property `classifierName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`classifierName`, "EXPECTED_RESULT")
})

test_that("taxonomyClasses", {
  # tests for the property `taxonomyClasses` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`taxonomyClasses`, "EXPECTED_RESULT")
})

