# NamSor API v2
#
# NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
#
# The version of the OpenAPI document: 2.0.10
# Contact: contact@namsor.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title BatchFirstLastNamePhoneCodedOut
#' @description BatchFirstLastNamePhoneCodedOut Class
#' @format An \code{R6Class} generator object
#' @field personalNamesWithPhoneNumbers  list( \link{FirstLastNamePhoneCodedOut} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BatchFirstLastNamePhoneCodedOut <- R6::R6Class(
  'BatchFirstLastNamePhoneCodedOut',
  public = list(
    `personalNamesWithPhoneNumbers` = NULL,
    initialize = function(`personalNamesWithPhoneNumbers`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`personalNamesWithPhoneNumbers`)) {
        stopifnot(is.vector(`personalNamesWithPhoneNumbers`), length(`personalNamesWithPhoneNumbers`) != 0)
        sapply(`personalNamesWithPhoneNumbers`, function(x) stopifnot(R6::is.R6(x)))
        self$`personalNamesWithPhoneNumbers` <- `personalNamesWithPhoneNumbers`
      }
    },
    toJSON = function() {
      BatchFirstLastNamePhoneCodedOutObject <- list()
      if (!is.null(self$`personalNamesWithPhoneNumbers`)) {
        BatchFirstLastNamePhoneCodedOutObject[['personalNamesWithPhoneNumbers']] <-
          lapply(self$`personalNamesWithPhoneNumbers`, function(x) x$toJSON())
      }

      BatchFirstLastNamePhoneCodedOutObject
    },
    fromJSON = function(BatchFirstLastNamePhoneCodedOutJson) {
      BatchFirstLastNamePhoneCodedOutObject <- jsonlite::fromJSON(BatchFirstLastNamePhoneCodedOutJson)
      if (!is.null(BatchFirstLastNamePhoneCodedOutObject$`personalNamesWithPhoneNumbers`)) {
        self$`personalNamesWithPhoneNumbers` <- ApiClient$new()$deserializeObj(BatchFirstLastNamePhoneCodedOutObject$`personalNamesWithPhoneNumbers`, "array[FirstLastNamePhoneCodedOut]", loadNamespace("namsor"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`personalNamesWithPhoneNumbers`)) {
        sprintf(
        '"personalNamesWithPhoneNumbers":
        [%s]
',
        paste(sapply(self$`personalNamesWithPhoneNumbers`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(BatchFirstLastNamePhoneCodedOutJson) {
      BatchFirstLastNamePhoneCodedOutObject <- jsonlite::fromJSON(BatchFirstLastNamePhoneCodedOutJson)
      self$`personalNamesWithPhoneNumbers` <- ApiClient$new()$deserializeObj(BatchFirstLastNamePhoneCodedOutObject$`personalNamesWithPhoneNumbers`, "array[FirstLastNamePhoneCodedOut]", loadNamespace("namsor"))
      self
    }
  )
)
