# NamSor API v2
#
# NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
#
# OpenAPI spec version: 2.0.11
# Contact: contact@namsor.com
# Generated by: https://openapi-generator.tech


#' BatchNameMatchedOut Class
#'
#' @field matchedNames 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BatchNameMatchedOut <- R6::R6Class(
  'BatchNameMatchedOut',
  public = list(
    `matchedNames` = NULL,
    initialize = function(`matchedNames`){
      if (!missing(`matchedNames`)) {
        stopifnot(is.list(`matchedNames`), length(`matchedNames`) != 0)
        lapply(`matchedNames`, function(x) stopifnot(R6::is.R6(x)))
        self$`matchedNames` <- `matchedNames`
      }
    },
    toJSON = function() {
      BatchNameMatchedOutObject <- list()
      if (!is.null(self$`matchedNames`)) {
        BatchNameMatchedOutObject[['matchedNames']] <- lapply(self$`matchedNames`, function(x) x$toJSON())
      }

      BatchNameMatchedOutObject
    },
    fromJSON = function(BatchNameMatchedOutJson) {
      BatchNameMatchedOutObject <- jsonlite::fromJSON(BatchNameMatchedOutJson)
      if (!is.null(BatchNameMatchedOutObject$`matchedNames`)) {
        self$`matchedNames` <- lapply(BatchNameMatchedOutObject$`matchedNames`, function(x) {
          matchedNamesObject <- NameMatchedOut$new()
          matchedNamesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          matchedNamesObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "matchedNames": [%s]
        }',
        lapply(self$`matchedNames`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(BatchNameMatchedOutJson) {
      BatchNameMatchedOutObject <- jsonlite::fromJSON(BatchNameMatchedOutJson)
      self$`matchedNames` <- lapply(BatchNameMatchedOutObject$`matchedNames`, function(x) NameMatchedOut$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
