# NamSor API v2
#
# NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 1000 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
#
# The version of the OpenAPI document: 2.0.3
# Contact: contact@namsor.com
# Generated by: https://openapi-generator.tech


#' CurrenciesOut Class
#'
#' @field currenciesIso3 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CurrenciesOut <- R6::R6Class(
  'CurrenciesOut',
  public = list(
    `currenciesIso3` = NULL,
    initialize = function(`currenciesIso3`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`currenciesIso3`)) {
        stopifnot(is.vector(`currenciesIso3`), length(`currenciesIso3`) != 0)
        sapply(`currenciesIso3`, function(x) stopifnot(is.character(x)))
        self$`currenciesIso3` <- `currenciesIso3`
      }
    },
    toJSON = function() {
      CurrenciesOutObject <- list()
      if (!is.null(self$`currenciesIso3`)) {
        CurrenciesOutObject[['currenciesIso3']] <-
          self$`currenciesIso3`
      }

      CurrenciesOutObject
    },
    fromJSON = function(CurrenciesOutJson) {
      CurrenciesOutObject <- jsonlite::fromJSON(CurrenciesOutJson)
      if (!is.null(CurrenciesOutObject$`currenciesIso3`)) {
        self$`currenciesIso3` <- ApiClient$new()$deserializeObj(CurrenciesOutObject$`currenciesIso3`, "array[character]", "package:namsor")
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`currenciesIso3`)) {
        sprintf(
        '"currenciesIso3":
           [%s]
        ',
        paste(unlist(lapply(self$`currenciesIso3`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CurrenciesOutJson) {
      CurrenciesOutObject <- jsonlite::fromJSON(CurrenciesOutJson)
      self$`currenciesIso3` <- ApiClient$new()$deserializeObj(CurrenciesOutObject$`currenciesIso3`, "array[character]","package:namsor")
      self
    }
  )
)
