# NamSor API v2
#
# NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
#
# The version of the OpenAPI document: 2.0.10
# Contact: contact@namsor.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FirstLastNameUSRaceEthnicityOut
#' @description FirstLastNameUSRaceEthnicityOut Class
#' @format An \code{R6Class} generator object
#' @field id  character [optional]
#'
#' @field firstName  character [optional]
#'
#' @field lastName  character [optional]
#'
#' @field raceEthnicityAlt  character [optional]
#'
#' @field raceEthnicity  character [optional]
#'
#' @field score  numeric [optional]
#'
#' @field raceEthnicitiesTop  list( character ) [optional]
#'
#' @field probabilityCalibrated  numeric [optional]
#'
#' @field probabilityAltCalibrated  numeric [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FirstLastNameUSRaceEthnicityOut <- R6::R6Class(
  'FirstLastNameUSRaceEthnicityOut',
  public = list(
    `id` = NULL,
    `firstName` = NULL,
    `lastName` = NULL,
    `raceEthnicityAlt` = NULL,
    `raceEthnicity` = NULL,
    `score` = NULL,
    `raceEthnicitiesTop` = NULL,
    `probabilityCalibrated` = NULL,
    `probabilityAltCalibrated` = NULL,
    initialize = function(`id`=NULL, `firstName`=NULL, `lastName`=NULL, `raceEthnicityAlt`=NULL, `raceEthnicity`=NULL, `score`=NULL, `raceEthnicitiesTop`=NULL, `probabilityCalibrated`=NULL, `probabilityAltCalibrated`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`firstName`)) {
        stopifnot(is.character(`firstName`), length(`firstName`) == 1)
        self$`firstName` <- `firstName`
      }
      if (!is.null(`lastName`)) {
        stopifnot(is.character(`lastName`), length(`lastName`) == 1)
        self$`lastName` <- `lastName`
      }
      if (!is.null(`raceEthnicityAlt`)) {
        stopifnot(is.character(`raceEthnicityAlt`), length(`raceEthnicityAlt`) == 1)
        self$`raceEthnicityAlt` <- `raceEthnicityAlt`
      }
      if (!is.null(`raceEthnicity`)) {
        stopifnot(is.character(`raceEthnicity`), length(`raceEthnicity`) == 1)
        self$`raceEthnicity` <- `raceEthnicity`
      }
      if (!is.null(`score`)) {
        stopifnot(is.numeric(`score`), length(`score`) == 1)
        self$`score` <- `score`
      }
      if (!is.null(`raceEthnicitiesTop`)) {
        stopifnot(is.vector(`raceEthnicitiesTop`), length(`raceEthnicitiesTop`) != 0)
        sapply(`raceEthnicitiesTop`, function(x) stopifnot(is.character(x)))
        self$`raceEthnicitiesTop` <- `raceEthnicitiesTop`
      }
      if (!is.null(`probabilityCalibrated`)) {
        stopifnot(is.numeric(`probabilityCalibrated`), length(`probabilityCalibrated`) == 1)
        self$`probabilityCalibrated` <- `probabilityCalibrated`
      }
      if (!is.null(`probabilityAltCalibrated`)) {
        stopifnot(is.numeric(`probabilityAltCalibrated`), length(`probabilityAltCalibrated`) == 1)
        self$`probabilityAltCalibrated` <- `probabilityAltCalibrated`
      }
    },
    toJSON = function() {
      FirstLastNameUSRaceEthnicityOutObject <- list()
      if (!is.null(self$`id`)) {
        FirstLastNameUSRaceEthnicityOutObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`firstName`)) {
        FirstLastNameUSRaceEthnicityOutObject[['firstName']] <-
          self$`firstName`
      }
      if (!is.null(self$`lastName`)) {
        FirstLastNameUSRaceEthnicityOutObject[['lastName']] <-
          self$`lastName`
      }
      if (!is.null(self$`raceEthnicityAlt`)) {
        FirstLastNameUSRaceEthnicityOutObject[['raceEthnicityAlt']] <-
          self$`raceEthnicityAlt`
      }
      if (!is.null(self$`raceEthnicity`)) {
        FirstLastNameUSRaceEthnicityOutObject[['raceEthnicity']] <-
          self$`raceEthnicity`
      }
      if (!is.null(self$`score`)) {
        FirstLastNameUSRaceEthnicityOutObject[['score']] <-
          self$`score`
      }
      if (!is.null(self$`raceEthnicitiesTop`)) {
        FirstLastNameUSRaceEthnicityOutObject[['raceEthnicitiesTop']] <-
          self$`raceEthnicitiesTop`
      }
      if (!is.null(self$`probabilityCalibrated`)) {
        FirstLastNameUSRaceEthnicityOutObject[['probabilityCalibrated']] <-
          self$`probabilityCalibrated`
      }
      if (!is.null(self$`probabilityAltCalibrated`)) {
        FirstLastNameUSRaceEthnicityOutObject[['probabilityAltCalibrated']] <-
          self$`probabilityAltCalibrated`
      }

      FirstLastNameUSRaceEthnicityOutObject
    },
    fromJSON = function(FirstLastNameUSRaceEthnicityOutJson) {
      FirstLastNameUSRaceEthnicityOutObject <- jsonlite::fromJSON(FirstLastNameUSRaceEthnicityOutJson)
      if (!is.null(FirstLastNameUSRaceEthnicityOutObject$`id`)) {
        self$`id` <- FirstLastNameUSRaceEthnicityOutObject$`id`
      }
      if (!is.null(FirstLastNameUSRaceEthnicityOutObject$`firstName`)) {
        self$`firstName` <- FirstLastNameUSRaceEthnicityOutObject$`firstName`
      }
      if (!is.null(FirstLastNameUSRaceEthnicityOutObject$`lastName`)) {
        self$`lastName` <- FirstLastNameUSRaceEthnicityOutObject$`lastName`
      }
      if (!is.null(FirstLastNameUSRaceEthnicityOutObject$`raceEthnicityAlt`)) {
        self$`raceEthnicityAlt` <- FirstLastNameUSRaceEthnicityOutObject$`raceEthnicityAlt`
      }
      if (!is.null(FirstLastNameUSRaceEthnicityOutObject$`raceEthnicity`)) {
        self$`raceEthnicity` <- FirstLastNameUSRaceEthnicityOutObject$`raceEthnicity`
      }
      if (!is.null(FirstLastNameUSRaceEthnicityOutObject$`score`)) {
        self$`score` <- FirstLastNameUSRaceEthnicityOutObject$`score`
      }
      if (!is.null(FirstLastNameUSRaceEthnicityOutObject$`raceEthnicitiesTop`)) {
        self$`raceEthnicitiesTop` <- ApiClient$new()$deserializeObj(FirstLastNameUSRaceEthnicityOutObject$`raceEthnicitiesTop`, "array[character]", loadNamespace("namsor"))
      }
      if (!is.null(FirstLastNameUSRaceEthnicityOutObject$`probabilityCalibrated`)) {
        self$`probabilityCalibrated` <- FirstLastNameUSRaceEthnicityOutObject$`probabilityCalibrated`
      }
      if (!is.null(FirstLastNameUSRaceEthnicityOutObject$`probabilityAltCalibrated`)) {
        self$`probabilityAltCalibrated` <- FirstLastNameUSRaceEthnicityOutObject$`probabilityAltCalibrated`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`firstName`)) {
        sprintf(
        '"firstName":
          "%s"
                ',
        self$`firstName`
        )},
        if (!is.null(self$`lastName`)) {
        sprintf(
        '"lastName":
          "%s"
                ',
        self$`lastName`
        )},
        if (!is.null(self$`raceEthnicityAlt`)) {
        sprintf(
        '"raceEthnicityAlt":
          "%s"
                ',
        self$`raceEthnicityAlt`
        )},
        if (!is.null(self$`raceEthnicity`)) {
        sprintf(
        '"raceEthnicity":
          "%s"
                ',
        self$`raceEthnicity`
        )},
        if (!is.null(self$`score`)) {
        sprintf(
        '"score":
          %d
                ',
        self$`score`
        )},
        if (!is.null(self$`raceEthnicitiesTop`)) {
        sprintf(
        '"raceEthnicitiesTop":
           [%s]
        ',
        paste(unlist(lapply(self$`raceEthnicitiesTop`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`probabilityCalibrated`)) {
        sprintf(
        '"probabilityCalibrated":
          %d
                ',
        self$`probabilityCalibrated`
        )},
        if (!is.null(self$`probabilityAltCalibrated`)) {
        sprintf(
        '"probabilityAltCalibrated":
          %d
                ',
        self$`probabilityAltCalibrated`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FirstLastNameUSRaceEthnicityOutJson) {
      FirstLastNameUSRaceEthnicityOutObject <- jsonlite::fromJSON(FirstLastNameUSRaceEthnicityOutJson)
      self$`id` <- FirstLastNameUSRaceEthnicityOutObject$`id`
      self$`firstName` <- FirstLastNameUSRaceEthnicityOutObject$`firstName`
      self$`lastName` <- FirstLastNameUSRaceEthnicityOutObject$`lastName`
      self$`raceEthnicityAlt` <- FirstLastNameUSRaceEthnicityOutObject$`raceEthnicityAlt`
      self$`raceEthnicity` <- FirstLastNameUSRaceEthnicityOutObject$`raceEthnicity`
      self$`score` <- FirstLastNameUSRaceEthnicityOutObject$`score`
      self$`raceEthnicitiesTop` <- ApiClient$new()$deserializeObj(FirstLastNameUSRaceEthnicityOutObject$`raceEthnicitiesTop`, "array[character]", loadNamespace("namsor"))
      self$`probabilityCalibrated` <- FirstLastNameUSRaceEthnicityOutObject$`probabilityCalibrated`
      self$`probabilityAltCalibrated` <- FirstLastNameUSRaceEthnicityOutObject$`probabilityAltCalibrated`
      self
    }
  )
)
