# NamSor API v2
#
# NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 1000 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
#
# OpenAPI spec version: 2.0.2-beta
# Contact: contact@namsor.com
# Generated by: https://openapi-generator.tech


#' FirstLastNameDiasporaedOut Class
#'
#' @field id 
#' @field firstName 
#' @field lastName 
#' @field score 
#' @field ethnicityAlt 
#' @field ethnicity 
#' @field countryIso2 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FirstLastNameDiasporaedOut <- R6::R6Class(
  'FirstLastNameDiasporaedOut',
  public = list(
    `id` = NULL,
    `firstName` = NULL,
    `lastName` = NULL,
    `score` = NULL,
    `ethnicityAlt` = NULL,
    `ethnicity` = NULL,
    `countryIso2` = NULL,
    initialize = function(`id`, `firstName`, `lastName`, `score`, `ethnicityAlt`, `ethnicity`, `countryIso2`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`firstName`)) {
        stopifnot(is.character(`firstName`), length(`firstName`) == 1)
        self$`firstName` <- `firstName`
      }
      if (!missing(`lastName`)) {
        stopifnot(is.character(`lastName`), length(`lastName`) == 1)
        self$`lastName` <- `lastName`
      }
      if (!missing(`score`)) {
        stopifnot(is.numeric(`score`), length(`score`) == 1)
        self$`score` <- `score`
      }
      if (!missing(`ethnicityAlt`)) {
        stopifnot(is.character(`ethnicityAlt`), length(`ethnicityAlt`) == 1)
        self$`ethnicityAlt` <- `ethnicityAlt`
      }
      if (!missing(`ethnicity`)) {
        stopifnot(is.character(`ethnicity`), length(`ethnicity`) == 1)
        self$`ethnicity` <- `ethnicity`
      }
      if (!missing(`countryIso2`)) {
        stopifnot(is.character(`countryIso2`), length(`countryIso2`) == 1)
        self$`countryIso2` <- `countryIso2`
      }
    },
    toJSON = function() {
      FirstLastNameDiasporaedOutObject <- list()
      if (!is.null(self$`id`)) {
        FirstLastNameDiasporaedOutObject[['id']] <- self$`id`
      }
      if (!is.null(self$`firstName`)) {
        FirstLastNameDiasporaedOutObject[['firstName']] <- self$`firstName`
      }
      if (!is.null(self$`lastName`)) {
        FirstLastNameDiasporaedOutObject[['lastName']] <- self$`lastName`
      }
      if (!is.null(self$`score`)) {
        FirstLastNameDiasporaedOutObject[['score']] <- self$`score`
      }
      if (!is.null(self$`ethnicityAlt`)) {
        FirstLastNameDiasporaedOutObject[['ethnicityAlt']] <- self$`ethnicityAlt`
      }
      if (!is.null(self$`ethnicity`)) {
        FirstLastNameDiasporaedOutObject[['ethnicity']] <- self$`ethnicity`
      }
      if (!is.null(self$`countryIso2`)) {
        FirstLastNameDiasporaedOutObject[['countryIso2']] <- self$`countryIso2`
      }

      FirstLastNameDiasporaedOutObject
    },
    fromJSON = function(FirstLastNameDiasporaedOutJson) {
      FirstLastNameDiasporaedOutObject <- jsonlite::fromJSON(FirstLastNameDiasporaedOutJson)
      if (!is.null(FirstLastNameDiasporaedOutObject$`id`)) {
        self$`id` <- FirstLastNameDiasporaedOutObject$`id`
      }
      if (!is.null(FirstLastNameDiasporaedOutObject$`firstName`)) {
        self$`firstName` <- FirstLastNameDiasporaedOutObject$`firstName`
      }
      if (!is.null(FirstLastNameDiasporaedOutObject$`lastName`)) {
        self$`lastName` <- FirstLastNameDiasporaedOutObject$`lastName`
      }
      if (!is.null(FirstLastNameDiasporaedOutObject$`score`)) {
        self$`score` <- FirstLastNameDiasporaedOutObject$`score`
      }
      if (!is.null(FirstLastNameDiasporaedOutObject$`ethnicityAlt`)) {
        self$`ethnicityAlt` <- FirstLastNameDiasporaedOutObject$`ethnicityAlt`
      }
      if (!is.null(FirstLastNameDiasporaedOutObject$`ethnicity`)) {
        self$`ethnicity` <- FirstLastNameDiasporaedOutObject$`ethnicity`
      }
      if (!is.null(FirstLastNameDiasporaedOutObject$`countryIso2`)) {
        self$`countryIso2` <- FirstLastNameDiasporaedOutObject$`countryIso2`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "firstName": %s,
           "lastName": %s,
           "score": %d,
           "ethnicityAlt": %s,
           "ethnicity": %s,
           "countryIso2": %s
        }',
        self$`id`,
        self$`firstName`,
        self$`lastName`,
        self$`score`,
        self$`ethnicityAlt`,
        self$`ethnicity`,
        self$`countryIso2`
      )
    },
    fromJSONString = function(FirstLastNameDiasporaedOutJson) {
      FirstLastNameDiasporaedOutObject <- jsonlite::fromJSON(FirstLastNameDiasporaedOutJson)
      self$`id` <- FirstLastNameDiasporaedOutObject$`id`
      self$`firstName` <- FirstLastNameDiasporaedOutObject$`firstName`
      self$`lastName` <- FirstLastNameDiasporaedOutObject$`lastName`
      self$`score` <- FirstLastNameDiasporaedOutObject$`score`
      self$`ethnicityAlt` <- FirstLastNameDiasporaedOutObject$`ethnicityAlt`
      self$`ethnicity` <- FirstLastNameDiasporaedOutObject$`ethnicity`
      self$`countryIso2` <- FirstLastNameDiasporaedOutObject$`countryIso2`
    }
  )
)
