# NamSor API v2
#
# NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 1000 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
#
# OpenAPI spec version: 2.0.2-beta
# Contact: contact@namsor.com
# Generated by: https://openapi-generator.tech


#' FirstLastNamePhoneNumberIn Class
#'
#' @field id 
#' @field firstName 
#' @field lastName 
#' @field phoneNumber 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FirstLastNamePhoneNumberIn <- R6::R6Class(
  'FirstLastNamePhoneNumberIn',
  public = list(
    `id` = NULL,
    `firstName` = NULL,
    `lastName` = NULL,
    `phoneNumber` = NULL,
    initialize = function(`id`=NULL, `firstName`=NULL, `lastName`=NULL, `phoneNumber`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`firstName`)) {
        stopifnot(is.character(`firstName`), length(`firstName`) == 1)
        self$`firstName` <- `firstName`
      }
      if (!is.null(`lastName`)) {
        stopifnot(is.character(`lastName`), length(`lastName`) == 1)
        self$`lastName` <- `lastName`
      }
      if (!is.null(`phoneNumber`)) {
        stopifnot(is.character(`phoneNumber`), length(`phoneNumber`) == 1)
        self$`phoneNumber` <- `phoneNumber`
      }
    },
    toJSON = function() {
      FirstLastNamePhoneNumberInObject <- list()
      if (!is.null(self$`id`)) {
        FirstLastNamePhoneNumberInObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`firstName`)) {
        FirstLastNamePhoneNumberInObject[['firstName']] <-
          self$`firstName`
      }
      if (!is.null(self$`lastName`)) {
        FirstLastNamePhoneNumberInObject[['lastName']] <-
          self$`lastName`
      }
      if (!is.null(self$`phoneNumber`)) {
        FirstLastNamePhoneNumberInObject[['phoneNumber']] <-
          self$`phoneNumber`
      }

      FirstLastNamePhoneNumberInObject
    },
    fromJSON = function(FirstLastNamePhoneNumberInJson) {
      FirstLastNamePhoneNumberInObject <- jsonlite::fromJSON(FirstLastNamePhoneNumberInJson)
      if (!is.null(FirstLastNamePhoneNumberInObject$`id`)) {
        self$`id` <- FirstLastNamePhoneNumberInObject$`id`
      }
      if (!is.null(FirstLastNamePhoneNumberInObject$`firstName`)) {
        self$`firstName` <- FirstLastNamePhoneNumberInObject$`firstName`
      }
      if (!is.null(FirstLastNamePhoneNumberInObject$`lastName`)) {
        self$`lastName` <- FirstLastNamePhoneNumberInObject$`lastName`
      }
      if (!is.null(FirstLastNamePhoneNumberInObject$`phoneNumber`)) {
        self$`phoneNumber` <- FirstLastNamePhoneNumberInObject$`phoneNumber`
      }
    },
    toJSONString = function() {
      sprintf(
        '{
           "id":
             "%s",
           "firstName":
             "%s",
           "lastName":
             "%s",
           "phoneNumber":
             "%s"
        }',
        self$`id`,
        self$`firstName`,
        self$`lastName`,
        self$`phoneNumber`
      )
    },
    fromJSONString = function(FirstLastNamePhoneNumberInJson) {
      FirstLastNamePhoneNumberInObject <- jsonlite::fromJSON(FirstLastNamePhoneNumberInJson)
      self$`id` <- FirstLastNamePhoneNumberInObject$`id`
      self$`firstName` <- FirstLastNamePhoneNumberInObject$`firstName`
      self$`lastName` <- FirstLastNamePhoneNumberInObject$`lastName`
      self$`phoneNumber` <- FirstLastNamePhoneNumberInObject$`phoneNumber`
      self
    }
  )
)
